[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_cpi = "4zFsVBdd3q6jNZWZ3DSSFTvm7yS8TnwfEM2Eq4Gzdeb4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/acammm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
